package com.zipper.sign.gdbh.bean

data class CheckInBody(
    val avatar: String = "",
    val balance: String = "",
    val branch_date: Int = 0,
    val branch_rate: Int = 0,
    val branch_role: Int = 0,
    val city: String = "",
    val created_date: String = "",
    val created_time: String = "",
    val credits: String = "",
    val fans: String = "",
    val gender: String = "",
    val income: String = "",
    val invite_code: String = "",
    val logined_time: String = "",
    val member_id: String = "",
    val member_name: String = "",
    val member_role: String = "",
    val openid: String = "",
    val phone: String = "",
    val platform: String = "",
    val pname: String = "",
    val prole: String = "",
    val province: String = "",
    val pwechat: String = "",
    val qq: String = "",
    val remark: Any? = null,
    val status: String = "",
    val unionid: String = "",
    val updated_time: Any? = null,
    val validity: String = "",
    val wechat: String = ""
)